//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClothForArms
{
    using System;
    using System.Collections.Generic;
    
    public partial class Material
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Material()
        {
            this.Supplier = new HashSet<Supplier>();
        }
    
        public int Id { get; set; }
        public string Title { get; set; }
        public Nullable<int> MaterialTypeId { get; set; }
        public string Image { get; set; }
        public Nullable<decimal> Cost { get; set; }
        public Nullable<int> CountInStock { get; set; }
        public Nullable<int> MinCount { get; set; }
        public Nullable<int> CountInPack { get; set; }
        public string Unit { get; set; }
        public string Description { get; set; }
    
        public virtual MaterialType MaterialType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Supplier> Supplier { get; set; }
    }
}
